In [2]:
import numpy as np
import pandas as pd
import  matplotlib.pyplot as mlt

In [3]:
df=pd.read_csv("C:/Users/knvss/OneDrive/Desktop/winequalityN.csv")

In [4]:
print(df)

       type  fixed acidity  volatile acidity  citric acid  residual sugar  \
0     white            7.0             0.270         0.36            20.7   
1     white            6.3             0.300         0.34             1.6   
2     white            8.1             0.280         0.40             6.9   
3     white            7.2             0.230         0.32             8.5   
4     white            7.2             0.230         0.32             8.5   
...     ...            ...               ...          ...             ...   
6492    red            6.2             0.600         0.08             2.0   
6493    red            5.9             0.550         0.10             2.2   
6494    red            6.3             0.510         0.13             2.3   
6495    red            5.9             0.645         0.12             2.0   
6496    red            6.0             0.310         0.47             3.6   

      chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  

In [5]:
x= df.iloc[:, [2,3]].values  
y= df.iloc[:, 4].values  

In [7]:
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.25, random_state=0)  

In [8]:
from sklearn.preprocessing import StandardScaler    
st_x= StandardScaler()    
x_train= st_x.fit_transform(x_train)    
x_test= st_x.transform(x_test)       

In [9]:
print(x)

[[0.27  0.36 ]
 [0.3   0.34 ]
 [0.28  0.4  ]
 ...
 [0.51  0.13 ]
 [0.645 0.12 ]
 [0.31  0.47 ]]


In [10]:
print(y)

[20.7  1.6  6.9 ...  2.3  2.   3.6]


In [11]:
print(x_train)

[[ 1.53658158e-03 -4.01597829e-01]
 [ 4.82282973e-01  2.93510919e+00]
 [ 1.14330926e+00 -1.93092188e+00]
 ...
 [-5.85567173e-02 -2.62568370e-01]
 [-4.79209809e-01  8.50052783e-02]
 [ 1.02312266e+00  1.54520008e-01]]


In [13]:
print(x_test)

[[ 0.24190978  1.33627041]
 [ 0.72265617 -0.05402418]
 [-0.8397696   0.64112312]
 ...
 [-0.35902321  0.64112312]
 [-0.8397696   0.29354947]
 [ 1.32358916 -1.65286296]]


In [4]:
np.unique(df.quality.values.tolist())


NameError: name 'np' is not defined